apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hipster-shop-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: ["adservice","cartservice","checkoutservice","currencyservice","emailservice","frontend","paymentservice","productcatalogservice","recommendationservice","shippingservice"]}
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: grpc
      interval: 15s
      path: /metrics
      scheme: http

